[project]
name = "agent-memory-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai-agents>=0.2.3",
    "openai[agents]>=1.97.1",
    "python-dotenv>=1.1.1",
]
